### ISSUE TITLE
Feature: Fitbit API access

### ISSUE THREAD

**Issue by mousekoz** [mousekoz/fitbitgcalsync#1]
Authenticate and fetch period cycle data.

**Comment by mousekoz** [comment]
**Tasks**
- [ ] Set up OAuth2 authentication for Fitbit
- [ ] Write script to fetch user's cycle data
- [ ] Parse and format the data

**Comment by mousekoz** [comment]
Fitbit Web API uses a common implementation of the OAuth 2.0 specification.
https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/

Need a Python OAuth 2.0 or HTTP client library.

**Comment by mousekoz** [comment]
- [ ]     Request authorization from a user to access their data.
- [ ]     Query the user's data using the provided access token.
- [ ]     Refresh expired access tokens with the corresponding refresh token.
